### ISSUE TITLE
Elasticsearch::Drain::Autoscaling#instance returning NilClass

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/elasticsearch-drain#5]
For what ever reason we are returning nil from:
https://github.com/rapid7/elasticsearch-drain/blob/master/lib/elasticsearch/drain/autoscaling.rb#L60

```
/Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-drain-0.0.2/lib/elasticsearch/drain/cli.rb:58:in `block in remove_nodes': undefined method `instance_id' for nil:NilClass (NoMethodError)
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-drain-0.0.2/lib/elasticsearch/drain/cli.rb:57:in `each'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-drain-0.0.2/lib/elasticsearch/drain/cli.rb:57:in `remove_nodes'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-drain-0.0.2/lib/elasticsearch/drain/cli.rb:25:in `asg'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /Users/rvanburen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/elasticsearch-drain-0.0.2/bin/drain:3:in `<top (required)>'
from /Users/rvanburen/.rbenv/versions/2.2.2/bin/drain:23:in `load'
from /Users/rvanburen/.rbenv/versions/2.2.2/bin/drain:23:in `<main>’
```

**Comment by athompson-r7** [comment]
This might be related to #4
